/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Colors directly mapped from Stitch config
        "tertiary": "#7e3000",
        "surface-container-high": "#eae6f4",
        "on-tertiary": "#ffffff",
        "on-background": "#1b1b24",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f3effc",
        "surface-container": "#f0ecf9",
        "secondary": "#58579b",
        "surface-container-low": "#f5f2ff",
        "on-primary-fixed-variant": "#3323cc",
        "on-secondary-fixed-variant": "#413f82",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "secondary-container": "#b6b4ff",
        "background": "#fcf8ff",
        "secondary-fixed": "#e2dfff",
        "primary-fixed-dim": "#c3c0ff",
        "surface-tint": "#4d44e3",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb695",
        "secondary-fixed-dim": "#c3c0ff",
        "outline": "#777587",
        "on-secondary-fixed": "#140f54",
        "inverse-primary": "#c3c0ff",
        "surface-container-highest": "#e4e1ee",
        "on-surface-variant": "#464555",
        "surface-variant": "#e4e1ee",
        "on-secondary-container": "#454386",
        "primary-container": "#4f46e5",
        "inverse-surface": "#302f39",
        "on-primary-fixed": "#0f0069",
        "on-secondary": "#ffffff",
        "on-primary-container": "#dad7ff",
        "on-tertiary-container": "#ffd2be",
        "tertiary-container": "#a44100",
        "surface-dim": "#dcd8e5",
        "outline-variant": "#c7c4d8",
        "on-tertiary-fixed": "#351000",
        "on-surface": "#1b1b24",
        "tertiary-fixed": "#ffdbcc",
        "error": "#ba1a1a",
        "primary-fixed": "#e2dfff",
        "primary": {
          DEFAULT: "#4f46e5", // mapped slightly to indigo-600
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
          950: '#1e1b4b',
        },
        "surface-bright": "#fcf8ff",
        "surface": "#fcf8ff",
        // Keep accent color just in case
        accent: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
          950: '#052e16',
        },
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "3xl": "1.5rem"
      },
      fontFamily: {
        body: ['var(--font-manrope)', 'sans-serif'],
        manrope: ['var(--font-manrope)', 'sans-serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-out forwards',
        'slide-up': 'slideUp 0.5s ease-out forwards',
        'pulse-soft': 'pulseSoft 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '.5' },
        },
      },
    },
  },
  plugins: [],
}
